### ISSUE TITLE
Update RNA-seq data analysis tutorial to use Get External Data in Excel instead of simply opening tsv

### ISSUE THREAD

**Issue by khanspers** [cytoscape/cytoscape-tutorials#104]
Currently the tutorial says to just open tsv in Excel. Because of the issues with Excel interpreting some gene names as dates and changing them. Instead the tutorial should instruct users to launch Excel, open blank doc, then go to Data > Get External Data and import the tsv. During import, the Gene Name column type should be switched to "text" instead of "general".

**Comment by AlexanderPico** [comment]
should we switch to csv?

**Comment by khanspers** [comment]
Good idea, we can switch to csv also.

**Comment by khanspers** [comment]
The relevant slide has been updated: https://cytoscape.org/cytoscape-tutorials/protocols/rna-seq-data-analysis/#/background

The file is only available as tsv from Expression Atlas, so if we wanted to switch to csv we need to change how the file is retrieved and host a local csv copy. Not a problem but Im not sure if it makes a difference really.
