### ISSUE TITLE
Replace example dataset for RNA-Seq Data Analysis protocol

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/cytoscape-tutorials#114]
I know we've gone back and forth on this, but currently the intro experience with the public dataset is very bad for this tutorial:
https://cytoscape.org/cytoscape-tutorials/protocols/rna-seq-data-analysis/#/

Attached is a simplified version of the dataset that they won't have to tweak at all in Excel. It's pre-filtered for significant up and down genes and the columns are relabeled.

Otherwise the tutorial steps can be the same, but this will give a red-blue divergent gradient and more interesting experience.

[rna-seq-data-cytoscape.csv](https://github.com/user-attachments/files/17528235/rna-seq-data-cytoscape.csv)

**Comment by AlexanderPico** [comment]
Upload to this folder: cytoscape-tutorials/protocols/rna-seq-data-analysis/

And after the tutorial site is rebuilt it should be accessible from this link:
https://cytoscape.org/cytoscape-tutorials/protocols/rna-seq-data-analysis/rna-seq-data-cytoscape.csv

**Comment by khanspers** [comment]
So the STRING query would include all genes in the new input file, up and down, correct? The resulting network would look something like this:

<img width="867" alt="Screen Shot 2024-10-25 at 5 45 59 PM" src="https://github.com/user-attachments/assets/489a4b89-95da-42be-8573-58f7a3849102">
