### ISSUE TITLE
Add cybrowser links to protocols

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/cytoscape-tutorials#2]
Demo the [first protocol](https://cytoscape.github.io/cytoscape-tutorials/protocols/basic-data-visualization.html#/) with cybrowser links.  Ideally, every protocol would have such links to support in-app interactivity.

**Comment by khanspers** [comment]
https://cytoscape.github.io/cytoscape-tutorials/protocols/modules/basic-data-visualization/#/
