### ISSUE TITLE
Basic visualization tutorial questions

### ISSUE THREAD

**Issue by jimhu-tamu** [cytoscape/cytoscape-tutorials#25]
This may be related to/mergeable with #3 

I just started with Cytoscape but also am teaching it in a new modular graduate class. I started with the [basic data visualization tutorial](https://cytoscape.github.io/cytoscape-tutorials/protocols/modules/basic-data-visualization/#/) but realized I had some questions about the provenance of the data being used, where understanding that would improve my ability to both answer questions and extend the lesson to related learning objectives. 

From the content of the tables pane, I inferred that the data being used is the same as what is included in the sampleData directory that comes with the CytoScape distribution. Based on the README in that directory, I am guessing about where the data comes from:
## Gene expression
The README refers to
Ideker, T., Thorsson V, Ranish JA, Christmas R, Buhler J, Eng JK, Bumgarner R, Goodlett DR, Aebersold R, Hood L. Integrated genomic and proteomic analyses of a systematically perturbed metabolic network. Science, 292, 929-34 (2001).

I found the paper and downloaded the Excel file in the supplemental data. The README describes galExpData.csv as including information about 20 perturbations, but I think it's only 3 of the 20 in the paper. The column headings do not match those in the supplemental data. My guess is that the names are based on gene + condition + exp for expression or sig for significance (error bars?), where the 3 genes are knockouts of GAL1, GAL4, and GAL80, and the conditions are raffinose only (R) or raffinose + galactose (RG). 

Thus the column that is the focus of the tutorial is gal80 knockout grown in raffinose, which is related to column V (gal80-gal) in the supplemental data file from Ideker et al. gal1RGexp is related to column E (gal1+gal) and gal4RGexp is related to column H (gal4 + gal). I couldn't find the data on either NCBI GEO or ArrayExpress.

- are these guesses correct?
 - if yes, the numerical values don't match and it's not clear how the values were processed to generate the numbers provided.
 - if no, where does the data come from?

## Interactions
Based on the identifiers, I'm guessing that the galFiltered.* comes from the yeastHighQuality.sif based on the von Mering and Lee papers. But again, the workflow for going from the supplemental data of the papers to the sif is not clear.

Thanks for any insight you can give on these.

**Comment by khanspers** [comment]
Hi Jim,
Thank you for your interest in Cytoscape, and for including it in your class!
You are correct that the data is from the Ideker publication, and you are also correct that the distributed data is a subset of the full dataset. I believe the mappings between columns that you propose are correct, but since the numbers don't match I think the data must have been further processed before being packaged with the Cytoscape distribution. The fact that the data is very old makes it difficult to track down, as the original people involved have left our team. We will be revamping our basic tutorial content with new data that will be clearly explained. Until then, I am trying to find an answer for you regarding this data.
Regards,
Kristina

**Comment by AlexanderPico** [comment]
Echoing Kristina's comments. The galFiltered.sif network has been the main "toy" network for the project for many many years. No one in the group was involved in the original research. I would only consider them loosely related. If you want active research examples, I'd look elsewhere. We are working on these in areas of automation, for example: https://github.com/cytoscape/cytoscape-automation/blob/master/for-scripters/R/advanced-cancer-networks-and-data-rcy3.Rmd

But the *point* of all of these is to learn the tool and we don't aim to discuss biological discovery with these examples. 

If you work out new examples with biological discovery as the point, please consider sharing them through our open repos:
- https://github.com/cytoscape/cytoscape-tutorials
- https://github.com/cytoscape/cytoscape-automation

Thanks.
