### ISSUE TITLE
Add id mapping to Loading Omics Data protocol

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/cytoscape-tutorials#26]
https://cytoscape.github.io/cytoscape-tutorials/protocols/modules/loading-omics-data/#/0/3

Make the dataset a bit harder (i.e., more realistic) with Entrez IDs. Then require ID Mapping (form Ensembl to Entrez) before importing data. Etc...

**Comment by khanspers** [comment]
The module linked to in the original description doesn't exist anymore. An ID mapping step used to be part of the [RNA-Seq protocol](https://cytoscape.org/cytoscape-tutorials/protocols/rna-seq-data-analysis/#/), but we removed it. I can review and potentially add it back

We also now have a dedicated ID mapping protocol:
https://cytoscape.org/cytoscape-tutorials/protocols/identifier-mapping/#/
