### ISSUE TITLE
updates to tutorials

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/cytoscape-tutorials#27]
- [x] generate icon for new Cytoscape App category, e.g., https://fontawesome.com/icons/plus-square?style=regular&from=io
- [x] add wikipathways logo to app protocol
- [x] update title and other aspects of WP protocol to be "the" official app protocol for WP
- [x] remove pngs from tutorial subfolders, should be in assets

**Comment by khanspers** [comment]
- Generate icon: http://fa2png.io/ seems to be down for maintenance. Will look for alternative.
- First pass at converting "pathway data viz" tutorial to official "wp app" tutorial done. Maybe needs another example.

**Comment by khanspers** [comment]
Done
