### ISSUE TITLE
New protocol: Getting Started Tour 

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/cytoscape-tutorials#3]
Create a protocol with cybrowser links that is intended for new users of Cytoscape. A link within Cytoscape would open the protocol and provide an interactive tour of basic features.

**Comment by khanspers** [comment]
Is this it? https://cytoscape.github.io/cytoscape-tutorials/protocols/modules/basic-data-visualization/#/

Or are we looking for more of a tour of the interface, menus, more generalized etc?

**Comment by khanspers** [comment]
https://cytoscape.github.io/cytoscape-tutorials/protocols/tour-of-cytoscape/#/
