### ISSUE TITLE
Trouble with the basic data visualization tutorial:  Dataset seems incomplete

### ISSUE THREAD

**Issue by scottedmands** [cytoscape/cytoscape-tutorials#49]
I am trying to use the basic data visualization tutorial.  I followed the steps for importing the GAL1 GAL4 GAL80 galFiltered network.  The data set that downloads does not look like the one in the tutorial and is limited to two columns:  "shared name" and "name".  There are no other columns with expression data so once you get to changing the fill color etc, there are no columns with meaningful data to select.
[Gal1Gal4Gal80filtered network.docx](https://github.com/cytoscape/cytoscape-tutorials/files/5064770/Gal1Gal4Gal80filtered.network.docx)

**Comment by AlexanderPico** [comment]
Thanks for reporting!

As you indicated, it looks like the network at NDEx does not have the node data. I think the tutorial used to have that as a separate step. Perhaps while consolidating, it was left out. Will add tutorial author to this issue.

**Comment by khanspers** [comment]
Hi @scottedmands. Sorry about the tutorial issue. I have added the correct network to NDEx and updated the tutorial with the name of the new network to load.

**Comment by scottedmands** [comment]
Thank you!
