### ISSUE TITLE
Formula for SLIST in new column

### ISSUE THREAD

**Issue by ARW-UBT** [cytoscape/cytoscape-tutorials#54]
Hi, 
How do I transfer parts of a string from one column to a new column by a function? 
The existing columns do contain strings separated by ';', and I would like to transfer e.g. the third string of one cell into the new column. 

Example: a column contains this taxonomic information: 
d__Eukaryota;p__Basidiomycota;c__Agaricomycetes;o__Trechisporales;f__Hydnodontaceae;g__Trechispora
I would like to transfer the 3rd element (c__Agaricomycetes) into a new column. 

I thought it should be possible with a function, but I could not fine the correct syntax to 1) split a string by a character (;) and transfer the 3rd string into the new field. 
f(x)=SLIST($label...

Is RegEx possible in Catoscape?

Thank you for any suggestions!

![grafik](https://user-images.githubusercontent.com/16762238/115703307-44bc8b00-a36a-11eb-8071-1c69291b92ee.png)

**Comment by mikekucera** [comment]
Its not currently possible to split a string on a delimiter with functions in Cytoscape. You have to do the processing in an external application like excel or with a script and then load the data into Cytoscape. 

I think adding more functions for string processing is a great idea though. I will add it to the list of features for Cytoscape 3.9.

**Comment by mikekucera** [comment]
https://cytoscape.atlassian.net/browse/CSD-518

**Comment by ARW-UBT** [comment]
Thanks for your fast answer. Would be great to have it. Microbiome networks gain more and more attentiion, and the gml data used above originated from one of the most important tools in this field: Qiime2. Therefor, many colleagues would appreciate it. 
Best regards!
