### ISSUE TITLE
16s micrbiome network analysis 

### ISSUE THREAD

**Issue by marwa38** [cytoscape/cytoscape-tutorials#59]
Hello 

I am new to cytoscape. 

Could you please share with me a tutorial or simple steps to how to do network analysis of a 16s rRNA microbiome data I have collected?

Thanks very much 
Marwa

**Comment by AlexanderPico** [comment]
Hi. All the available tutorials are found on the wiki page of this repo. There are none specific to 16s rRNA that I’m aware of. You might try asking biology questions on a forum of bioinformatics like BioStars.

**Comment by marwa38** [comment]
Thank for your prompt reply. @AlexanderPico 
Why I am asking about 16s as the inputs in the tutorials are network but I have phyloseq object which contains taxonomy table and features table (ASVs), have you heard about using different inputs before? phyloseq people don't know how to do so in cytoscape? this will be so helfpul

**Comment by AlexanderPico** [comment]
I'm not familiar with phyloseq or ASVs.  The only thing I've worked with involving phylogenetic trees is this R-based conversion of the Newick tree format to Cytoscape networks: https://cytoscape.org/cytoscape-automation/for-scripters/R/notebooks/Phylogenetic-trees.nb.html.

**Comment by marwa38** [comment]
Thanks very much @AlexanderPico
