### ISSUE TITLE
network analysis of PICRUST2 pathway outputs (KEGG, etc)?

### ISSUE THREAD

**Issue by marwa38** [cytoscape/cytoscape-tutorials#62]
Hello

Could you please share with me a tutorial or simple steps on how to do network analysis of picrust2 KEGG pathways?
Can I visualise the network of pathways?

Thanks very much
Marwa

**Comment by khanspers** [comment]
Hi. I haven't used the picrust tool before, but it seems possible to visualize the results in Cytoscape. I will look into it and let you know.

**Comment by marwa38** [comment]
Many thanks, Kristina @khanspers 
Looking forward

**Comment by marwa38** [comment]
Hi Kristina @khanspers 
Please let me know if would like to have some data outputs form picrust2. 
Cheers

**Comment by khanspers** [comment]
Sure that would be great. Please send it to kristina.hanspers@gladstone.ucsf.edu
