### ISSUE TITLE
Error importing files

### ISSUE THREAD

**Issue by akettring** [cytoscape/cytoscape-tutorials#70]
I'll premise this by saying I'm not a novice with cytoscape. I have used this program for several years.

While working on a network, I was applying a new layout (yFiles). It seemed to freeze so I used task manager to end the cytoscape process. Now I can't import any new networks at all. I get the following error: 'No edges will be created in the network; the source column is not selected. Do you want to continue?'

I am most definitely selecting a column for source (green circle) and destination (green triangle). I created a basic example in excel with 3 columns and 3 rows to ensure it wasn't my dataset. Still nothing.

[import table](https://imgur.com/a/wbWfjbA)
[import error](https://imgur.com/a/TG7Si4c)

I uninstalled cytoscape. I restarted the computer. I deleted the 'CytoscapeConfiguration' folder for my user directory. I deleted all registry keys that I could find searching for 'cytoscape'.  I reinstalled cytoscape. I still get the same error. I have tried this a few times now. Still nothing works.

Any help would be greatly appreciated.

**Comment by AlexanderPico** [comment]
Ah, the destination (or target) is the concentric red/white circles, like a target practice. The trainable is for interaction types. 

http://manual.cytoscape.org/en/stable/Creating_Networks.html#basic-operations

 - Alex

**Comment by akettring** [comment]
Wow I feel really dumb. Thank you! Haha.
