### ISSUE TITLE
Cyscape can't open Cys file

### ISSUE THREAD

**Issue by taoshengqiansui** [cytoscape/cytoscape-tutorials#74]
Cyscape can't open Cys file, and every time it is opened, it will get stuck. The same goes for uninstalling Cyscape and reinstalling it. Cys file is fine, you can open it with another computer's cytoscape.

**Comment by khanspers** [comment]
Hi. Please repost your question to cytoscape-helpdesk@googlegroups.com, and include details on operating system, Cytoscape version, and if possible supply the session file.

**Comment by khanspers** [comment]
@taoshengqiansui : Was this issue resolved?
